# Generated by Django 3.1.2 on 2020-11-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for the promo', max_length=140)),
                ('date', models.DateTimeField(auto_now=True, help_text='Date for the promo. If it is year long, put the end date')),
                ('description', models.TextField(blank=True, help_text='Description for the resource')),
                ('link', models.URLField(blank=True, help_text='Link to the website assoicated')),
                ('photo', models.ImageField(upload_to='static/img/promo')),
            ],
        ),
        migrations.CreateModel(
            name='resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for the promo', max_length=140)),
                ('description', models.TextField(blank=True, help_text='Description for the resource')),
                ('date', models.DateTimeField(auto_now=True, help_text='Date the resource was created')),
                ('photo', models.ImageField(upload_to='static/img/resource')),
            ],
        ),
    ]
