# Generated by Django 3.1.2 on 2020-11-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviromentApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='email',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='promo',
            name='date',
            field=models.DateTimeField(help_text='Date for the promo. If it is year long, put the end date'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='photo',
            field=models.ImageField(default='static/img/logo.png', upload_to='static/img/promo'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='date',
            field=models.DateTimeField(help_text='Date the resource was created'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='photo',
            field=models.ImageField(default='static/img/logo.png', upload_to='static/img/resource'),
        ),
    ]
