# Generated by Django 3.1.2 on 2020-11-06 01:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviromentApp', '0002_auto_20201104_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 20, 5, 12, 751775), help_text='Date for the promo. If it is year long, put the end date'),
        ),
    ]
