# Generated by Django 3.1.2 on 2020-11-06 01:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviromentApp', '0003_auto_20201105_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 20, 14, 47, 962800), help_text='Date for the promo. If it is year long, put the end date'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 20, 14, 48, 12801), help_text='Date the resource was created'),
        ),
    ]
