# Generated by Django 3.1.2 on 2020-11-10 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviromentApp', '0012_auto_20201108_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='date',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='date',
        ),
        migrations.AddField(
            model_name='promo',
            name='dateOfEvent',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 10, 15, 34, 30, 538480), help_text='Date for the promo. If it is year long, put the end date'),
        ),
        migrations.AddField(
            model_name='resource',
            name='dateOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 10, 15, 34, 30, 538480), help_text='Date the resource was created'),
        ),
    ]
