# Generated by Django 3.1.2 on 2020-11-10 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviromentApp', '0014_auto_20201110_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='dateOfEvent',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 10, 15, 52, 33, 772908), help_text='Date for the promo. If it is year long, put the end date'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='dateOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 10, 15, 52, 33, 773907), help_text='Date the resource was created'),
        ),
    ]
