# Generated by Django 3.1.2 on 2020-11-10 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviromentApp', '0015_auto_20201110_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='date',
            new_name='dateOfCreation',
        ),
        migrations.AlterField(
            model_name='promo',
            name='dateOfEvent',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 10, 16, 28, 34, 125809), help_text='Date for the promo. If it is year long, put the end date'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='dateOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 10, 16, 28, 34, 126807), help_text='Date the resource was created'),
        ),
    ]
