# Generated by Django 3.1.2 on 2020-11-10 16:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enviromentApp', '0016_auto_20201110_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='dateOfEvent',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date for the promo. If it is year long, put the end date'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='dateOfCreation',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date the resource was created'),
        ),
    ]
