# Generated by Django 3.1.2 on 2020-11-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviromentApp', '0017_auto_20201110_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='hashCode',
            field=models.CharField(default=None, max_length=32, unique=True),
        ),
    ]
