# Generated by Django 3.1.2 on 2020-11-17 13:00

from django.db import migrations, models
import enviromentApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('enviromentApp', '0019_auto_20201117_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='hashCode',
            field=models.CharField(default=enviromentApp.models.email.createHash, max_length=32),
        ),
    ]
