# Generated by Django 3.1.2 on 2020-11-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviromentApp', '0024_auto_20201130_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='photo',
            field=models.ImageField(default='frontend/static/img/logo.png', upload_to='frontend/static/img/promo'),
        ),
    ]
