# Generated by Django 3.1.2 on 2020-12-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviromentApp', '0025_auto_20201130_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='photo',
            field=models.ImageField(default='frontend/static/img/logo.png', upload_to='frontend/public/img/promo'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='photo',
            field=models.ImageField(default='frontend/static/img/logo.png', upload_to='frontend/public/img/resource'),
        ),
    ]
