# Generated by Django 3.1.2 on 2020-12-22 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviromentApp', '0026_auto_20201222_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='photo',
            field=models.ImageField(default='frontend/static/img/logo.png', upload_to='frontend/public/img/promotions'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='photo',
            field=models.ImageField(default='frontend/static/img/logo.png', upload_to='frontend/public/img/resources'),
        ),
    ]
