# Generated by Django 3.1.2 on 2020-12-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviromentApp', '0027_auto_20201222_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='link',
            field=models.URLField(blank=True, help_text='Link to the website assoicated'),
        ),
    ]
