# Generated by Django 3.1.2 on 2020-12-22 23:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enviromentApp', '0029_auto_20201222_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promo',
            old_name='dateOfEvent',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='dateOfCreation',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='email',
            name='dateOfCreation',
        ),
        migrations.AddField(
            model_name='email',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date the email was added to the list'),
            preserve_default=False,
        ),
    ]
