# Generated by Django 3.1.2 on 2020-12-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviromentApp', '0030_auto_20201222_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='photo',
            field=models.ImageField(default='frontend/public/img/logo.svg', upload_to='frontend/public/img/promotions'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='photo_description',
            field=models.TextField(default='Description for the image', help_text='Description for the image'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='photo',
            field=models.ImageField(default='frontend/public/img/logo.svg', upload_to='frontend/public/img/resources'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='photo_description',
            field=models.TextField(default='Description for the image', help_text='Description for the image'),
        ),
    ]
