# Generated by Django 3.1.2 on 2020-12-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviromentApp', '0032_auto_20201225_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='photo',
            field=models.ImageField(default='static/logo.svg', upload_to='static/promotions'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='photo',
            field=models.ImageField(default='static/logo.svg', upload_to='static/resources'),
        ),
    ]
