# Generated by Django 3.1.2 on 2020-12-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviromentApp', '0034_auto_20201225_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='photo',
            field=models.ImageField(default='static/logo.svg', upload_to=''),
        ),
    ]
