# Generated by Django 3.1.2 on 2020-12-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviromentApp', '0035_auto_20201225_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='photo',
            field=models.ImageField(default='/logo.svg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='resource',
            name='photo',
            field=models.ImageField(default='/logo.svg', upload_to=''),
        ),
    ]
