# Generated by Django 3.1.2 on 2020-12-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviromentApp', '0036_auto_20201225_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='photo',
            field=models.ImageField(default='/logo.svg', help_text='There is a bug with looking up images when you click on the link. You must change media to static and it will work', upload_to=''),
        ),
        migrations.AlterField(
            model_name='resource',
            name='photo',
            field=models.ImageField(default='/logo.svg', help_text='There is a bug with looking up images when you click on the link. You must change media to static and it will work', upload_to=''),
        ),
    ]
