# Generated by Django 3.1.2 on 2020-12-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviromentApp', '0037_auto_20201226_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='photo',
            field=models.ImageField(default='/logo.svg', help_text='Try to make each photo the same size(i.e 1080x1080)', upload_to=''),
        ),
        migrations.AlterField(
            model_name='resource',
            name='photo',
            field=models.ImageField(default='/logo.svg', help_text='Try to make each photo the same size(i.e 1080x1080)', upload_to=''),
        ),
    ]
